<?php
/**
 * @author Harry Tang <harry@modernkernel.com>
 * @link https://modernkernel.com
 * @copyright Copyright (c) 2017 Modern Kernel
 */


namespace modernkernel\contact\widgets;


use modernkernel\contact\models\Setting;
use yii\base\Widget;

/**
 * Class Info
 * @package modernkernel\contact\widgets
 */
class Info extends Widget
{

    /**
     * @inheritdoc
     * @return string
     */
    public function run()
    {

        parent::run(); // TODO: Change the autogenerated stub
        $settings = Setting::loadAsArray();
        return $this->render('info', ['settings'=>$settings]);
    }
}