<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2017 Power Kernel
 */


namespace powerkernel\contact\widgets;


use powerkernel\contact\models\Setting;
use yii\base\Widget;

/**
 * Class Info
 * @package powerkernel\contact\widgets
 */
class Info extends Widget
{

    /**
     * @inheritdoc
     * @return string
     */
    public function run()
    {

        parent::run(); // TODO: Change the autogenerated stub
        $settings = Setting::loadAsArray();
        return $this->render('info', ['settings'=>$settings]);
    }
}